import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { LINES, FAMILY_ORDER, buildMarkers, familyOf } from "./catalog-builder.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const markers = buildMarkers();

const header = `// Generated by scripts/build-catalog.mjs — do not edit by hand.
// Source: data/ohuhu.csv (Ohuhu unified color codes per the 2025 renumbering, plus 2026 additions).
// Original dataset by MysticSparkleWings (github.com/MysticSparkleWings/OhuhuPaletteGenerator).
// Hex values are approximate (approximate swatch reproductions).
// Retired markers (e.g. GY163 Green Bice) are kept so you can still find them, but can't be wished.
import type { CatalogMarker, Line } from "./types";

export const CATALOG: CatalogMarker[] = [`;

const body = markers
  .map((m) => {
    const oldCodes = m.lines.length
      ? `oldCodes: { ${m.lines.map((l) => `"${l}": "${m.oldCodes[l]}"`).join(", ")} }`
      : "oldCodes: {}";
    const retired = m.retired ? ", retired: true" : "";
    return `  { id: "${m.id}", code: "${m.code}", name: "${m.name}", hex: "${m.hex}", family: "${m.family}", lines: [${m.lines.map((l) => `"${l}"`).join(", ")}], ${oldCodes}${retired} },`;
  })
  .join("\n");

const labels = {
  red: "Reds", orange: "Oranges", yellow: "Yellows", green: "Greens",
  teal: "Teals", blue: "Blues", violet: "Violets", pink: "Pinks", neutral: "Neutrals",
};
const hues = {
  red: 0, orange: 25, yellow: 50, green: 120, teal: 180, blue: 215,
  violet: 265, pink: 315, neutral: 0,
};

const families = FAMILY_ORDER.map(
  (key) => `  { key: "${key}", label: "${labels[key]}", hue: ${hues[key]} },`,
).join("\n");

const footer = `];

export const CATALOG_BY_ID: Record<string, CatalogMarker> = Object.fromEntries(
  CATALOG.map((m) => [m.id, m]),
);

export const FAMILIES: { key: string; label: string; hue: number }[] = [
${families}
];

export const LINE_NAMES: Line[] = ${JSON.stringify(LINES)};`;

writeFileSync(
  resolve(__dirname, "../lib/catalogData.ts"),
  `${header}\n${body}\n${footer}\n`,
);

console.log(`Generated ${markers.length} markers into lib/catalogData.ts`);
for (const family of FAMILY_ORDER) {
  const count = markers.filter((m) => m.family === family).length;
  console.log(`  ${family}: ${count}`);
}